Controllers/AvenirTelecomMonthPlanController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Nop.Core;
using Nop.Core.Domain.Catalog;
using Nop.Services.Catalog;
using Nop.Services.Helpers;
using Nop.Services.Localization;
using Nop.Web.Framework.Kendoui;
using Nop.Plugin.Misc.AvenirTelecom.Models;
using System.Collections.Generic;
using System.Globalization;
using Nop.Services.Media;
using Nop.Plugin.Misc.AvenirTelecom.Services;
using Nop.Plugin.Misc.AvenirTelecom.Domain;
using Nop.Web.Framework.Mvc;
using Nop.Core.Caching;
using Nop.Services.Security;
using Nop.Services.Tax;
using Nop.Services.Directory;
using Nop.Core.Data;
using Nop.Plugin.Misc.AvenirTelecom.Helper;
using Nop.Services.Configuration;
using Nop.Services.Topics;
using Nop.Services.Common;

namespace Nop.Plugin.Misc.AvenirTelecom.Controllers
{
    public class AvenirTelecomMonthPlanController : Controller
    {
        #region Field

        private readonly IDateTimeHelper _dateTimeHelper;
        private readonly IWorkContext _workContext;
        private readonly CatalogSettings _catalogSettings;
        private readonly IProductService _productService;
        private readonly ILocalizationService _localizationService;
        private readonly ICategoryService _categoryService;
        private readonly IPictureService _pictureService;
        private readonly IAvenirTelecomMonthlyPlanService _avenirTelecomMonthlyPlanService;
        private readonly IWebHelper _webHelper;
        private readonly IStoreContext _storeContext;
        private readonly ICacheManager _cacheManager;
        private readonly IPermissionService _permissionService;
        private readonly IPriceCalculationService _priceCalculationService;
        private readonly ITaxService _taxService;
        private readonly ICurrencyService _currencyService;
        private readonly IPriceFormatter _priceFormatter;
        private readonly IProductAttributeService _productAttributeService;
        private readonly IPlanService _planService;
        private readonly IRepository<AvenirTelecomMonthlyPlan> _avenirTelecomMonthlyPlanRepository;
        private readonly IRepository<Plan> _planRepository;
        private readonly IRepository<PlanForSeed> _planSeedRepository;
        private readonly IRepository<Product> _productRepository;
        private readonly ISettingService _settingContext;
        private readonly ITopicService _topicService;
        private readonly IRepository<ProductAttribute> _productAttributeRepository;
        private readonly IGenericAttributeService _genericAttributeService;


        #endregion

        #region Ctr

        public AvenirTelecomMonthPlanController(IDateTimeHelper dateTimeHelper,
            IWorkContext workContext,
            CatalogSettings catalogSettings,
            IProductService productService,
            ILocalizationService localizationService,
            IPictureService pictureService,
            ICategoryService categoryService,
            IAvenirTelecomMonthlyPlanService avenirTelecomMonthlyPlanService,
            IWebHelper webHelper,
            IGenericAttributeService genericAttributeService,
            IStoreContext storeContext,
            ICacheManager cacheManager,
            IPermissionService permissionService,
            IPriceCalculationService priceCalculationService,
            ITaxService taxService,
            ICurrencyService currencyService,
            IPriceFormatter priceFormatter,
            IPlanService planService,
            IProductAttributeService productAttributeService,
            IRepository<AvenirTelecomMonthlyPlan> avenirTelecomMonthlyPlanRepository,
            IRepository<Product> productRepository,
            IRepository<Plan> planRepository,
            IRepository<PlanForSeed> planSeedRepository,
            ITopicService topicService,
            IRepository<ProductAttribute> productAttributeRepository,
        ISettingService settingContext)
        {
            _dateTimeHelper = dateTimeHelper;
            _settingContext = settingContext;
            _workContext = workContext;
            _catalogSettings = catalogSettings;
            _productService = productService;
            _localizationService = localizationService;
            _categoryService = categoryService;
            _productService = productService;
            _pictureService = pictureService;
            _avenirTelecomMonthlyPlanService = avenirTelecomMonthlyPlanService;
            _webHelper = webHelper;
            _genericAttributeService = genericAttributeService;
            _storeContext = storeContext;
            _cacheManager = cacheManager;
            _permissionService = permissionService;
            _priceCalculationService = priceCalculationService;
            _planService = planService;
            _taxService = taxService;
            _currencyService = currencyService;
            _priceFormatter = priceFormatter;
            _productAttributeService = productAttributeService;
            _avenirTelecomMonthlyPlanRepository = avenirTelecomMonthlyPlanRepository;
            _productRepository = productRepository;
            _planRepository = planRepository;
            _planSeedRepository = planSeedRepository;
            _topicService = topicService;
            _productAttributeRepository = productAttributeRepository;
        }

        #endregion

        #region Methods

        public ActionResult List()
        {
            var model = new ProductListModel();
            model.SearchIncludeSubCategories = false;
            var categories = _categoryService.GetAllCategories(showHidden: true);
            foreach (var c in categories)
            {
                model.AvailableCategories.Add(new SelectListItem { Text = c.GetFormattedBreadCrumb(categories), Value = c.Id.ToString() });
            }

            return View("~/Plugins/Misc.AvenirTelecom/Views/AvenirTelecomView/List.cshtml", model);
        }
        [HttpPost]
        public ActionResult ListJson(DataSourceRequest command, ProductListModel model)
        {
            var categoryIds = new List<int>() { model.CategoryId };
            model.CategoryId = model.CategoryId;
            model.SearchIncludeSubCategories = model.SearchIncludeSubCategories;

            //include subcategories
            if (model.SearchIncludeSubCategories && model.CategoryId > 0)
                categoryIds.AddRange(GetChildCategoryIds(model.CategoryId));

            var products = _productService.SearchProducts(
                categoryIds: categoryIds,
                pageIndex: command.Page - 1,
                pageSize: command.PageSize,
                showHidden: true
            );
            var gridModel = new DataSourceResult();
            gridModel.Data = products.Select(x =>
            {
                var defaultProductPicture = _pictureService.GetPicturesByProductId(x.Id).FirstOrDefault();
                return new ProductModel()
                {
                    Id = x.Id,
                    Add = 0,
                    DisableBuyButton = x.DisableBuyButton,
                    ShowOnHomePage = x.ShowOnHomePage,
                    Delete = 0,
                    ManageInventoryMethod = x.ManageInventoryMethod.GetLocalizedEnum(_localizationService, _workContext.WorkingLanguage.Id),
                    Name = x.Name,
                    OldPrice = x.OldPrice,
                    Price = x.Price,
                    Published = x.Published,
                    Sku = x.Sku,
                    StockQuantity = x.StockQuantity,
                    HasPlan = ifHasPlan(x.Id),
                    PictureThumbnailUrl = _pictureService.GetPictureUrl(defaultProductPicture, 75, true)
                };
            });
            gridModel.Total = products.TotalCount;
            //PublicPage();
            return Json(gridModel);
        }

        public ActionResult DeleteProductPlan(int productId = 0)
        {
            var allPlans = _avenirTelecomMonthlyPlanService.GetMounthlyPlanByProductId(productId);

            foreach (var plan in allPlans)
            {
                var planWithoutSubscription = plan.Plans.Where(x => x.SubscriptionType == 0).FirstOrDefault();
                if (planWithoutSubscription != null)
                {
                    var product = _productService.GetProductById(productId);
                    product.Price = planWithoutSubscription.MonthlyFeeForSubscription;
                    _productService.UpdateProduct(product);
                }
                plan.Plans.ToList().ForEach(x =>
                {
                    _planRepository.Delete(x);
                });
                _avenirTelecomMonthlyPlanService.DeleteAvenirTelecomMonthlyPlan(plan);
            }

            List<int> ProductVarientAttributeIds = new List<int>();
            List<string> AttributeValueNames = new List<string>
            {
                Constants.SubscriptionPlan,
                Constants.SubscriptionType,
                Constants.PlanType,
                Constants.PriceType
            };

            AttributeValueNames.ForEach(x =>
            {
                int id = _productAttributeRepository.Table.Where(pa => pa.Name.Equals(x)).FirstOrDefault().Id;
                var entity = _avenirTelecomMonthlyPlanService.GetEntityByProductAttributeId(productId, id);
                if (entity != null)
                {
                    ProductVarientAttributeIds.Add(entity.Id);
                    _productAttributeService.DeleteProductVariantAttribute(entity);
                }
            });

            ProductVarientAttributeIds.ForEach(x =>
            {
                var entityList = _productAttributeService.GetProductVariantAttributeValues(x);
                foreach (var s in entityList)
                {
                    _productAttributeService.DeleteProductVariantAttributeValue(s);
                }
            });

            //update product price
            try
            {

Views/AvenirTelecomView/IndividualPlanCreate.cshtml
@model Nop.Plugin.Misc.AvenirTelecom.Models.IndividualPlanViewModel
@using Nop.Web.Framework

@{  
    Layout = "~/Administration/Views/Shared/_AdminLayout.cshtml";  
    ViewBag.Title = T("Admin.Plugins.PlanEntry").Text;

    //Html.AddScriptParts("~/Plugins/Misc.AvenirTelecom/Content/js/jscolor.min.js");
}


<div>
        @using (Html.BeginForm())
            {
            <div class="section-header">
                <div class="title">
                    <img src="@Url.Content("~/Administration/Content/images/ico-content.png")" alt="" />
                    @T("Admin.Plugin.Misc.AvenirTelecom.DefaultSeeds.Create") <a href="/Plugin/Misc/AvenirTelecom/MonthlyPlan/@Model.ProductId">(@T("Admin.Plugin.Misc.AvenirTelecom.DefaultSeeds.BackToList"))</a>
                </div>
            </div>
            @Html.HiddenFor(model => model.ProductId)
            <table class="adminContent">
                <tr>
                    <td class="adminTitle">
                        Product Name:
                    </td>
                    <td class="adminData">
                        @Html.DisplayFor(model => model.ProductName, new { @readonly = "readonly" })
                    </td>
                </tr>
                <tr>
                    <td class="adminTitle">
                        @Html.LabelFor(model => model.SubscriptionPlan)
                    </td>
                    <td class="adminData">
                        @Html.TextBoxFor(model => model.SubscriptionPlan)
                    </td>
                </tr>               

                <tr>
                    <td class="adminTitle">
                        Subscription Type
                    </td>
                    <td class="adminData">
                        @Html.EnumDropDownListFor(m => m.SubscriptionType, "Select Subscription Type")
                    </td>
                </tr>
                <tr>
                    <td class="adminTitle">
                        Price Type
                    </td>
                    <td class="adminData">
                        @Html.EnumDropDownListFor(m => m.PriceType, "Select Price Type")
                    </td>
                </tr>

                <tr>
                    <td class="adminTitle">
                        @Html.LabelFor(model => model.MonthlyFeeForSubscription)

                    </td>
                    <td class="adminData">
                        @Html.TextBoxFor(model => model.MonthlyFeeForSubscription)
                    </td>
                </tr>

                <tr>
                    <td class="adminTitle">
                        @Html.LabelFor(model => model.CashPriceForDevice)

                    </td>
                    <td class="adminData">
                        @Html.TextBoxFor(model => model.CashPriceForDevice)
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <input type="submit" id="btnIndividualSave" name="save" class="k-button" value="@T("Admin.Common.Save")" />
                    </td>
                </tr>
            </table>


        }
</div>

Views/AvenirTelecomView/List.cshtml
@model Nop.Plugin.Misc.AvenirTelecom.Models.ProductListModel
@using Nop.Core.Infrastructure
@using Nop.Web.Framework
@{
    var defaultGridPageSize = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().DefaultGridPageSize;
    var gridPageSizes = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().GridPageSizes;

    Layout = "~/Administration/Views/Shared/_AdminLayout.cshtml";
    //page title
    ViewBag.Title = T("Admin.Plugins.AvenirTelecom").Text;

    string addButton = "<a href='MonthlyPlan/#=Id#' class='k-button'>@T('Admin.Add')</a>";
    string deleteButton = "<a href='MonthlyPlan/#=Id#' class='k-button'>@T('Admin.Del')</a>";
}

<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Administration/Content/images/ico-content.png")" alt="" />
        @T("Admin.Plugin.Misc.AvenirTelecom.Products.AddPlan")
</div>
    
</div>
<table width="100%">
    <tr>
        <td class="adminTitle">
            @Html.NopLabelFor(model => model.CategoryId):
        </td>
        <td class="adminData">
            @Html.DropDownList("CategoryId", Model.AvailableCategories)
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <table>
                <tr>
                    <td>
                        <input type="button" id="btnSearch" class="k-button" value="@T("Admin.Common.Search")" />
                    </td>
                </tr>
            </table>

        </td>

    </tr>
</table>
<table class="adminContent">
    <tr>
        <td>
            <div id="products-grid"></div>

            <script>
                $(document).ready(function() {
                    $("#products-grid").kendoGrid({
                        dataSource: {
                            type: "json",
                            transport: {
                                read: {
                                    url: "@Html.Raw(Url.Action("ListJson", "AvenirTelecomMonthPlan", new { area = "" }))",
                                    type: "POST",
                                    dataType: "json",
                                    data: additionalData
                                },
                                update: {
                                    url: "@Html.Raw(Url.Action("HomePageProductUpdate", "AvenirTelecomMonthPlan", new { categoryId = Model.CategoryId, area = "" }))",
                                    type: "POST",
                                    dataType: "json"
                                },

                                parameterMap: function(data, operation) {
                                    if (operation != "read") {
                                        //post the entities so the ASP.NET DefaultModelBinder will understand them:
                                        //products[0].Name="name"
                                        //products[0].Id = 1
                                        //products[1].Name="name"
                                        //products[1].Id = 1

                                        var result = {};

                                        for (var i = 0; i < data.models.length; i++) {
                                            var entity = data.models[i];

                                            for (var member in entity) {
                                                result["products[" + i + "]." + member] = entity[member];
                                            }
                                        }

                                        return result;
                                    } else {
                                        //return JSON.stringify(data);
                                        return data;
                                    }
                                }
                            },
                            schema: {
                                data: "Data",
                                total: "Total",
                                errors: "Errors",
                                model: {
                                    id: "Id",
                                    fields: {
                                        Id: { editable: false, type: "number" },
                                        Name: { editable: false, type: "string" },
                                        ProductId: { editable: false, type: "number" },
                                        Sku: { editable: true, type: "string" },
                                        Price: { editable: true, type: "number" },
                                        StockQuantity: { editable: false, type: "number" },
                                        Published: { editable: true, type: "boolean" }
                                    }
                                }
                            },
                            error: function(e) {
                                display_kendoui_grid_error(e);
                                // Cancel the changes
                                this.cancelChanges();
                            },
                            //bulk editing
                            batch: true,
                            pageSize: @(defaultGridPageSize),
                            serverPaging: true,
                            serverFiltering: true,
                            serverSorting: true
                        },
                        pageable: {
                            refresh: true,
                            pageSizes: [@(gridPageSizes)]
                        },
                        //toolbar: ["save", "cancel"],
                        editable: {
                            confirmation: false,
                            //bulk editing
                            mode: "incell"
                        },
                        scrollable: false,
                        columns: [
                             {
                                 field: "PictureThumbnailUrl",
                                 title: "@T("Admin.Catalog.Products.Fields.PictureThumbnailUrl")",
                                 template: '<img src="#=PictureThumbnailUrl#" />',
                                 width: 100
                             },
                            {
                                field: "Id",
                                title: "@T("Admin.Catalog.Products.Fields.Name")",
                                //template: '<a href="@Url.Content("~/Admin/Product/Edit/")#=Id#">#:Name#</a>'
                                template:"#if(!HasPlan){#<a href='/Admin/Product/Edit/#=Id#'>#:Name#</a>#}else{#<a href='/AvenirTelecomMonthPlan/MonthlyPlan/#=Id#'>#:Name# (View Plan)</a>#}#"
                   
                            },
                            {
                                field: "ShowOnHomePage",
                                title: "@T("ShowOnHomePage")",
                                width: 100
                            },
                            {
                                field: "Sku",
                                title: "@T("Admin.Catalog.BulkEdit.Fields.Sku")",
                                width: 150
                            },
                            {
                                field: "Price",
                                title: "@T("Admin.Catalog.BulkEdit.Fields.Price")",
                                width: 150,
                                editor: function (container, options) {
                                    $('<input name="' + options.field + '"/>')
                                        .appendTo(container)
                                        .kendoNumericTextBox({
                                            format: "{0:n4}",
                                            decimals: 4
                                        });
                                }
                            },
                            {
                                field: "StockQuantity",
                                title: "@T("Admin.Catalog.BulkEdit.Fields.StockQuantity")",
                                //integer format
                                format: "{0:0}",
                                width: 150
                            },
                            {
                                field: "Published",
                                title: "@T("Admin.Catalog.BulkEdit.Fields.Published")",
                                width: 200
                            },
                             {
                                 field: "Id",
                                 title: "@T("Add.MonthlyPlan")",
                                 encoded: false,
                                 width: 100,
                                 template:"#if(!HasPlan){#<a href='MonthlyPlan/#=Id#' class='k-button'>Add Plan</a>#}else{#<a href='/Plugin/Misc/AvenirTelecom/MonthlyPlan/Delete/#=Id#' class='k-button'>Remove Plan</a>#}#"
                   
                             }
                        ]
                    });
                });
            </script>

            <script type="text/javascript">

                $(document).ready(function () {
                    $('#btnSearch').click(function () {
                        var grid = $('#products-grid').data('kendoGrid');
                        grid.dataSource.page(1);
                        grid.refresh();
                        return false;
                    });
                });

                function additionalData()
                {
                    var data = {
                        CategoryId:$("#CategoryId").val(),
                        SearchIncludeSubCategories:true
                    };
                    //addAntiForgeryToken(data);
                    return data;
                }

            </script>
        </td>
    </tr>
</table>

Views/AvenirTelecomView/MonthlyPlan.cshtml
@model Nop.Plugin.Misc.AvenirTelecom.Models.AvenirTelecomMonthlyPlanModel
@using Nop.Core.Infrastructure
@using Nop.Web.Framework
@{

    var defaultGridPageSize = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().DefaultGridPageSize;
    var gridPageSizes = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().GridPageSizes;

    Layout = "~/Administration/Views/Shared/_AdminLayout.cshtml";
    //page title
    ViewBag.Title = T("Admin.Plugins.CategoryImage").Text;
}
<style>
    #CategoryName {
        border: none;
    }
</style>


@Html.HiddenFor(model => model.ProductId)
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Administration/Content/images/ico-content.png")" alt="" />
        @T("Admin.Plugin.Misc.AvenirTelecom.Product.MonthlyPlan.List")  - <a href="/Plugin/Misc/AvenirTelecom/List">(@T("Admin.Plugin.Misc.AvenirTelecom.Product.MonthlyPlan.BackToList"))</a>
    </div>
    <div class="options">
        <a href='@string.Format("/Plugin/Misc/AvenirTelecom/IndividualPlanCreate/{0}", Model.ProductId)' class="k-button">@T("Admin.Common.AddNew")</a>
    </div>
</div>
<p>Product Name : <b>  @Model.ProductName </b></p>

<div>
    <div id="monthlyplan-grid"></div>
    <script>
        $(document).ready(function () {
            $("#monthlyplan-grid").kendoGrid({
                dataSource: {
                    type: "json",
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("MonthlyPlanList", "AvenirTelecomMonthPlan", new { productId = Model.ProductId, area = "" }))",
                            type: "POST",
                            dataType: "json"
                        },
                        update: {
                            url: "@Html.Raw(Url.Action("UpdateMonthlyPlan", "AvenirTelecomMonthPlan", new { area = "" }))",
                            type: "POST",
                            dataType: "json"
                        },
                        destroy: {
                            url: "@Html.Raw(Url.Action("DeleteMonthlyPlan", "AvenirTelecomMonthPlan", new { id = Model.Id, area = "" }))",
                            type: "POST",
                            dataType: "json"
                        }
                    },
                    schema: {
                        data: "Data",
                        total: "Total",
                        errors: "Errors",
                        model: {
                            id: "Id",
                            fields: {
                                SubscriptionType: { editable: false, type: "string" },
                                PriceTypeName: { editable: false, type: "string" },
                                SubscriptionPlan: { editable: false, type: "string" },
                                CashPriceForDevice: { editable: true, type: "decimal" },
                                MonthlyFeeForSubscription: { editable: true, type: "decimal" },
                                SetAsDefaultPlan: { editable: true, type: "boolean" }
                            }
                        }
                    },
                    requestEnd: function (e) {
                        if (e.type == "update") {
                            this.read();
                        }
                    },
                    error: function (e) {
                        display_kendoui_grid_error(e);
                        // Cancel the changes
                        this.cancelChanges();
                    },
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },
                pageable: {
                    refresh: true,
                    numeric: false,
                    previousNext: false,
                    info: false
                },
                dataBound: onDataBound,
                editable: {
                    confirmation: false,
                    mode: "inline"
                },
                scrollable: false,
                columns: [
                    {
                        field: "SubscriptionType",
                        title: "Subscription Type",
                        width: 200
                    },
                    {
                        field: "PriceTypeName",
                        title: "@T("Price type Name")",
                        width: 200
                    },
                    {
                        field: "SubscriptionPlan",
                        title: "@T("Admin.Misc.AvenirTelecom.Fields.SubscriptionItemName")",
                        width: 200
                    },
                    {
                        field: "MonthlyFeeForSubscription",
                        title: "@T("Admin.Misc.AvenirTelecom.Fields.MonthlyFeeForSubscription")",
                        width: 200
                    },
                    {
                        field: "CashPriceForDevice",
                        title: "@T("Admin.Misc.AvenirTelecom.Fields.CashPriceForDevice")",
                        width: 200
                    },
                      {
                          field: "SetAsDefaultPlan",
                          title: "@T("Set As Default Plan")",
                          width: 200
                      },
                    {
                        command: [{
                            name: "edit",
                            text: "@T("Admin.Common.Edit")"
                        },
                        {
                            name: "destroy",
                            text: "@T("Admin.Common.Delete")"
                        }],
                        width: 200
                    }]
            });
        });
    </script>
    <script type="text/javascript">

        function onDataBound(e) {
            //if ($('#monthlyplan-grid img').length > 0) {
            //    $("#changeCategoryColor").css("display", "block");
            //}
        }
    </script>
</div>

Views/AvenirTelecomView/PriceHandle.cshtml
@using Nop.Core.Infrastructure
@using Nop.Web.Framework
@{
    var defaultGridPageSize = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().DefaultGridPageSize;
    var gridPageSizes = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().GridPageSizes;
    //page title
    ViewBag.Title = T("Admin.Plugins.Configure").Text;
}
<div>
    <a href="/HomePageProduct/CategoryAdd">(Back to plugin main page)</a>
    First you need to add @Html.Widget("category_wise_product") where you want to show the output
    then add Category then category product then category image and lastly add subcategory.
</div>

Views/AvenirTelecomView/_ChoiceModal.cshtml
<div  style="margin-top:50px;" class="modal fade" tabindex="-1" role="dialog" id="choicePlanModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Select Offer </h4>
            </div>

            <div class="modal-footer">
                <h5>Please select an offer for the purchase of this device / tariff plan:</h5>
                <button type="button" class="btn btn-danger" onclick="PTSimple.selectChoice(0);">New Service</button>
                <button type="button" class="btn btn-danger" onclick="PTSimple.selectChoice(1);">Change of plan</button>
                <button type="button" class="btn btn-danger" onclick="PTSimple.selectChoice(2);">Prima to subscription</button>
            </div>
        </div>
    </div>
</div>